name: e2e tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker-compose build
    - run: docker-compose run lib
      env:
        CI: true